apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: erpnext-mariadb
  namespace: mariadb
spec:
  #frappe only tested up to 10.8, looks like 10.6 is the latest maintained version
  image: docker-registry1.mariadb.com/library/mariadb:10.6

  replicas: 3
  galera:
    enabled: true
    config:
      reuseStorageVolume: true

  rootPasswordSecretKeyRef:
    name: erpnext-mariadb-root
    key: password
    generate: true

  username: erpnext
  passwordSecretKeyRef:
    name: erpnext-mariadb-password
    key: password
    generate: true

  #database: erpnext

  port: 3306

  storage:
    size: 16Gi
  #  storageClassName: standard
  #  resizeInUseVolumes: true
  #  waitForVolumeResize: true
  #  volumeClaimTemplate:
  #    accessModes:
  #    - ReadWriteOnce
  #    resources:
  #      requests:
  #        storage: 1Gi
  #    storageClassName: standard

  service:
    type: LoadBalancer
    metadata:
      annotations:
      #  metallb.universe.tf/loadBalancerIPs: 172.18.0.20
  
  #primaryService:
  #  type: LoadBalancer
  #  metadata:
  #    annotations:
  #    #  metallb.universe.tf/loadBalancerIPs: 172.18.0.20
#
  #secondaryService:
  #  type: LoadBalancer
  #  metadata:
  #    annotations:
  #    #  metallb.universe.tf/loadBalancerIPs: 172.18.0.20

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M
    slow_query_log
    long_query_time = 1

  metrics:
    enabled: true
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: erpnext-readonly
  namespace: mariadb
spec:
  # If you want the user to be created with a different name than the resource name
  # name: user-custom
  mariaDbRef:
    name: erpnext-mariadb
  passwordSecretKeyRef:
    name: erpnext-readonly
    key: password
  # This field defaults to 10
  maxUserConnections: 20
  host: "%"
  # Delete the resource in the database whenever the CR gets deleted.
  # Alternatively, you can specify Skip in order to omit deletion.
  #cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-erpnext-readonly
  namespace: mariadb
spec:
  mariaDbRef:
    name: erpnext-mariadb
  privileges:
    - "SELECT"
    # - "ALL PRIVILEGES"
  database: "*"
  table: "*"
  username: erpnext-readonly
  grantOption: false
  host: "%"
  # Delete the resource in the database whenever the CR gets deleted.
  # Alternatively, you can specify Skip in order to omit deletion.
  #cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s