apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: erpnext-mariadb
  namespace: mariadb
spec:
  #frappe only tested up to 10.8, looks like 10.6 is the latest maintained version
  image: docker-registry1.mariadb.com/library/mariadb:10.6
  rootPasswordSecretKeyRef:
    name: erpnext-mariadb-root
    key: password
    generate: true

  username: erpnext
  passwordSecretKeyRef:
    name: erpnext-mariadb-password
    key: password
    generate: true
  database: erpnext

  port: 3306

  storage:
    size: 4Gi

  service:
    type: LoadBalancer
    metadata:
      annotations:
      #  metallb.universe.tf/loadBalancerIPs: 172.18.0.20

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M

  metrics:
    enabled: true
