---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-cert
  namespace: gitlab-system
spec:
  dnsNames:
    - "*.sentracam.net"
  secretName: gitlab-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
---