---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shield-sentracam-com
  namespace: shield
spec:
  dnsNames:
    - "shield.sentracam.com"
  secretName: shield-sentracam-com-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shield-nginx
  namespace: shield
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shield-nginx
  template:
    metadata:
      labels:
        app: shield-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: static-files
          mountPath: /usr/share/nginx/html  # Default path for NGINX to serve files from
          subPath: MySentraCam/build/web
        - name: shield-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: static-files
        persistentVolumeClaim:
          claimName: shield-pvc  # Reference the PVC here
      - name: shield-config
        configMap:
          name: shield-config
---
apiVersion: v1
kind: Service
metadata:
  name: shield-nginx-service
  namespace: shield
spec:
  type: ClusterIP  # Can also be LoadBalancer or NodePort if needed
  selector:
    app: shield-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shield-nginx-ingress
  namespace: shield
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: shield.sentracam.com  # Replace with your desired domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shield-nginx-service
            port:
              number: 80
  tls:
  - hosts:
      - shield.sentracam.com
    secretName: shield-sentracam-com-tls
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shield-config
  namespace: shield
data:
  default.conf: |
    server {
        listen 80; 
        server_name shield.sentracam.com; 
        root /usr/share/nginx/html/;
        index index.html index.htm; 
        client_max_body_size 150M;
        large_client_header_buffers 4 512k;
        client_header_buffer_size 512k;
        access_log /var/log/nginx/shield.access.log;
        error_log /var/log/nginx/shield.error.log;

        location / { 
            try_files $uri $uri/ /index.html; 
        } 

        location /api/ {
            #proxy_set_header Host erp.sentracam.com;
            #proxy_pass https://erp.sentracam.com/api/;
            #proxy_ssl_server_name on;
            proxy_pass http://frappe-bench-erpnext.erpnext:8080/api/;
            proxy_set_header Host erp.sentracam.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /files/ {
        #    #proxy_set_header Host erp.sentracam.com;
        #    #proxy_pass https://erp.sentracam.com/files/;
        #    #proxy_ssl_server_name on;
            proxy_pass http://frappe-bench-erpnext.erpnext:8080/files/;
            proxy_set_header Host erp.sentracam.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /private/files/ {
        #    #proxy_set_header Host erp.sentracam.com;
        #    #proxy_pass https://erp.sentracam.com/private/files/;
        #    #proxy_ssl_server_name on;
            proxy_pass http://frappe-bench-erpnext.erpnext:8080/private/files/;
            proxy_set_header Host erp.sentracam.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /art/ {
            proxy_hide_header 'Access-Control-Allow-Origin';
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*' ;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' ;
                add_header "Access-Control-Allow-Headers" "Authorization, Origin, X-Requested-With, Content-Type, Accept";
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
                add_header 'Access-Control-Max-Age' 1728000;
                return 200;
            }
            if ($request_method = 'POST') {
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
                add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
            }
            if ($request_method = 'GET') {
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
                add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
            }
            proxy_pass https://art.sentracam.com:8080/art/;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp
  namespace: shield 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
    spec:
      containers:
      - name: sftp
        image: atmoz/sftp:alpine  
        ports:
        - containerPort: 22
        volumeMounts:
        - name: sftp-data
          mountPath: /home/shield/shield  
        env:
        - name: SFTP_USERS
          value: "shield:TopIsland21:1001:100"  # Add as many users as needed
      volumes:
      - name: sftp-data
        persistentVolumeClaim:
          claimName: shield-pvc  # Attach the PVC you created earlier
---
apiVersion: v1
kind: Service
metadata:
  name: sftp-service
  namespace: shield
spec:
  ports:
    - port: 22
      targetPort: 22
  selector:
    app: sftp
  type: LoadBalancer
  loadBalancerIP: 69.24.142.21
