apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: xwiki-mariadb
  namespace: mariadb
spec:
  image: docker-registry1.mariadb.com/library/mariadb:10.6
  #image: docker-registry1.mariadb.com/library/mariadb:lts

  replicas: 3
  galera:
    enabled: true
    config:
      reuseStorageVolume: true

  rootPasswordSecretKeyRef:
    name: xwiki-mariadb-root
    key: password
    generate: true

  username: xwiki
  passwordSecretKeyRef:
    name: xwiki-mariadb-password
    key: password
    generate: true
  
  #database: xwiki

  port: 3306

  storage:
    size: 16Gi
  #  storageClassName: standard
  #  resizeInUseVolumes: true
  #  waitForVolumeResize: true
  #  volumeClaimTemplate:
  #    accessModes:
  #    - ReadWriteOnce
  #    resources:
  #      requests:
  #        storage: 1Gi
  #    storageClassName: standard

  service:
    type: LoadBalancer
    metadata:
      annotations:
      #  metallb.universe.tf/loadBalancerIPs: 172.18.0.20
  
  #primaryService:
  #  type: LoadBalancer
  #  metadata:
  #    annotations:
  #    #  metallb.universe.tf/loadBalancerIPs: 172.18.0.20
#
  #secondaryService:
  #  type: LoadBalancer
  #  metadata:
  #    annotations:
  #    #  metallb.universe.tf/loadBalancerIPs: 172.18.0.20

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M

  metrics:
    enabled: true
